name: astrogenie
services:
  - name: web
    git:
      branch: main
      repo_clone_url: ${REPO_URL}
    build_command: npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs

  - name: api
    git:
      branch: main
      repo_clone_url: ${REPO_URL}
    build_command: npm install
    run_command: npm run api
    envs:
      - key: NODE_ENV
        value: production
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

static_sites:
  - name: client
    git:
      branch: main
      repo_clone_url: ${REPO_URL}
    build_command: npm run build
    output_dir: out
    envs:
      - key: NODE_ENV
        value: production
