[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "8.0.0"
